// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_shadow_co_lmg");
	self attach("head_shadow_co_b", "", true);
	self.headModel = "head_shadow_co_b";
	self.voice = "british";
}

precache()
{
	precacheModel("body_shadow_co_lmg");
	precacheModel("head_shadow_co_b");
}
