// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_riot_udt");
	self attach("head_riot_udt", "", true);
	self.voice = "british";
}

precache()
{
	precacheModel("body_riot_udt");
	precacheModel("head_riot_udt");
}
